export const DAILY_TARGETS = {
  calories: 2000,
  protein: 110,
};

export const sessions = [
  {
    id: "A",
    title: "Upper body + push-up skill",
    shortTitle: "Upper foundation",
    subtitle: "Push, pull and arms",
    duration: "50–58 min",
    tone: "coral",
    image: "/assets/workout-upper.webp",
    summary: "Your first priority session. Build pressing and pulling strength without chasing failure.",
    exercises: [
      {
        id: "a-incline-pushup",
        name: "Incline push-up",
        sets: 2,
        reps: "5–8 reps",
        rest: 60,
        effort: "Stop with 3 clean reps left",
        instructions: [
          "Use a stable bench height that allows at least five clean reps.",
          "Keep head, ribs, hips and knees in one straight line.",
          "Bring your chest between your hands; do not drop only your head.",
        ],
        caution: "Raise the incline if your hips sag or the shoulder hurts.",
      },
      {
        id: "a-chest-press",
        name: "Incline machine chest press",
        sets: 2,
        reps: "8–12 reps",
        rest: 90,
        effort: "3 reps in reserve",
        instructions: [
          "Follow the machine placard and set the handles around upper-to-mid chest in a pain-free range.",
          "Keep shoulder blades gently against the back pad.",
          "Keep elbows about 30–45° from your torso and move smoothly.",
        ],
        caution: "Reduce load or range once for joint pain. If it returns—or there is instability, numbness or sudden weakness—stop this movement and get assessed.",
      },
      {
        id: "a-pulldown",
        name: "Comfortable-grip lat pulldown",
        sets: 2,
        reps: "8–12 reps",
        rest: 90,
        effort: "2–3 reps in reserve",
        instructions: [
          "Lock your thighs under the pad and keep your ribs controlled.",
          "Pull elbows toward your sides without swinging backward.",
          "Return the bar slowly until the shoulders are comfortably long.",
        ],
        caution: "Do not pull behind your neck or use momentum.",
      },
      {
        id: "a-row",
        name: "Chest-supported or seated row",
        sets: 2,
        reps: "10–12 reps",
        rest: 90,
        effort: "2–3 reps in reserve",
        instructions: [
          "Sit tall with your chest supported when the machine allows it.",
          "Lead with the elbows and pause briefly when handles reach the torso.",
          "Keep shoulders away from your ears throughout.",
        ],
        caution: "Reduce the load if you need to lean or jerk.",
      },
      {
        id: "a-lateral-raise",
        name: "Light lateral raise",
        sets: 2,
        reps: "12–15 reps",
        rest: 60,
        effort: "3 reps in reserve",
        instructions: [
          "Use very light dumbbells or the cable machine.",
          "Keep soft elbows and lift slightly forward of directly sideways.",
          "Stop around shoulder height without shrugging.",
        ],
        caution: "This should feel like muscle work, not joint pain.",
      },
      {
        id: "a-triceps",
        name: "Rope triceps pressdown",
        sets: 2,
        reps: "10–15 reps",
        rest: 60,
        effort: "2–3 reps in reserve",
        instructions: [
          "Pin elbows near your sides and keep your torso still.",
          "Press down until the arms straighten without locking aggressively.",
          "Return under control without letting elbows drift forward.",
        ],
      },
      {
        id: "a-hammer-curl",
        name: "Dumbbell hammer curl",
        sets: 2,
        reps: "10–15 reps",
        rest: 60,
        effort: "2–3 reps in reserve",
        instructions: [
          "Hold the dumbbells with palms facing each other.",
          "Keep elbows close to your sides and avoid swinging.",
          "Lower each repetition slowly.",
        ],
      },
      {
        id: "a-cardio",
        name: "Pain-free cardio",
        sets: 1,
        reps: "10–12 min",
        rest: 0,
        effort: "Full sentences remain possible",
        instructions: [
          "Walk, cycle or use the elliptical at a moderate conversational pace.",
          "Slow the treadmill until you can move without holding the rails.",
        ],
        caution: "No running while the shin return gate is incomplete.",
      },
    ],
  },
  {
    id: "B",
    title: "Lower body + core",
    shortTitle: "Lower + core",
    subtitle: "Legs, shin capacity and trunk",
    duration: "50–58 min",
    tone: "aqua",
    image: "/assets/workout-lower.webp",
    summary: "A deliberately moderate leg session that supports body composition, running and future calisthenics.",
    exercises: [
      {
        id: "b-leg-press",
        name: "Leg press",
        sets: 2,
        reps: "8–12 reps",
        rest: 120,
        effort: "3 reps in reserve",
        instructions: [
          "Place feet about shoulder-width around the middle of the platform.",
          "Keep hips and lower back against the pad throughout.",
          "Lower only as far as you can keep that position; track knees with toes.",
        ],
        caution: "Do not slam or aggressively lock the knees.",
      },
      {
        id: "b-leg-curl",
        name: "Seated or lying leg curl",
        sets: 2,
        reps: "10–15 reps",
        rest: 90,
        effort: "2–3 reps in reserve",
        instructions: [
          "Align your knee with the machine pivot.",
          "Place the moving pad just above the ankle.",
          "Keep hips against the pad and curl without jerking.",
        ],
      },
      {
        id: "b-glute-bridge",
        name: "Glute bridge",
        sets: 2,
        reps: "10–15 reps",
        rest: 90,
        effort: "3 reps in reserve",
        instructions: [
          "Keep feet flat and close enough that shins are nearly vertical at the top.",
          "Keep ribs down, squeeze the glutes and lift smoothly.",
          "Stop before the lower back arches.",
        ],
      },
      {
        id: "b-calf",
        name: "Calf raise",
        sets: 2,
        reps: "12–15 reps",
        rest: 60,
        effort: "2–3 reps in reserve",
        instructions: [
          "Move through a comfortable range without bouncing.",
          "Pause briefly at the top and lower slowly.",
        ],
      },
      {
        id: "b-tibialis",
        name: "Wall-supported tibialis raise",
        sets: 2,
        reps: "15–20 reps",
        rest: 45,
        effort: "3 reps in reserve",
        instructions: [
          "Stand against a wall with feet slightly forward.",
          "Keep heels down and lift the front of both feet toward the shins.",
        ],
        caution: "Omit it if it reproduces shin-bone pain now or the next morning.",
      },
      {
        id: "b-plank",
        name: "Front plank",
        sets: 2,
        reps: "15–30 sec",
        rest: 60,
        effort: "Stop before form changes",
        instructions: [
          "Keep elbows under shoulders and gently push the floor away.",
          "Keep ribs and pelvis stacked; squeeze glutes lightly.",
          "End the set before hips sag or the lower back takes over.",
        ],
      },
      {
        id: "b-dead-bug",
        name: "Dead bug",
        sets: 2,
        reps: "6–10 / side",
        rest: 60,
        effort: "Slow and controlled",
        instructions: [
          "Gently press the lower back toward the floor.",
          "Extend one leg and the opposite arm only as far as the back stays still.",
          "Return slowly and switch sides.",
        ],
      },
      {
        id: "b-compression",
        name: "Seated single-leg compression",
        sets: 1,
        reps: "6–10 / side",
        rest: 45,
        effort: "Controlled",
        instructions: [
          "Sit near the edge of a stable bench with one leg straight.",
          "Place hands beside the thigh and lift the heel a few centimetres.",
          "Stay tall instead of leaning backward.",
        ],
      },
      {
        id: "b-cardio",
        name: "Pain-free cardio",
        sets: 1,
        reps: "10–12 min",
        rest: 0,
        effort: "Conversational pace",
        instructions: [
          "Choose walking, cycling or elliptical work.",
          "Keep the effort moderate and hands off treadmill rails.",
        ],
        caution: "Stop if shin symptoms appear.",
      },
    ],
  },
  {
    id: "C",
    title: "Full body + pull-up skill",
    shortTitle: "Full body",
    subtitle: "Pull-up practice and repeat exposure",
    duration: "50–58 min",
    tone: "violet",
    image: "/assets/workout-upper.webp",
    summary: "The third foundation session keeps every major area moving even during a three-day week.",
    exercises: [
      {
        id: "c-assisted-pullup",
        name: "Assisted pull-up or chin-up",
        sets: 2,
        reps: "4–6 reps",
        rest: 120,
        effort: "3 reps in reserve",
        instructions: [
          "Use enough assistance to move without kicking or shrugging.",
          "Start long, pull elbows toward your ribs and keep your neck neutral.",
          "Lower slowly to a comfortable full reach.",
        ],
        caution: "More selected weight on this machine usually means more assistance.",
      },
      {
        id: "c-chest-press",
        name: "Pain-free machine chest press",
        sets: 2,
        reps: "8–12 reps",
        rest: 90,
        effort: "2–3 reps in reserve",
        instructions: [
          "Repeat the same seat setting and pain-free range used in Session A.",
          "Keep shoulders against the pad and elbows below shoulder height.",
        ],
        caution: "Reduce load or range once for joint pain. If it returns—or there is instability, numbness or sudden weakness—stop this movement and get assessed.",
      },
      {
        id: "c-row",
        name: "Seated machine or cable row",
        sets: 2,
        reps: "8–12 reps",
        rest: 90,
        effort: "2–3 reps in reserve",
        instructions: [
          "Keep your torso quiet and pull the handles toward the lower ribs.",
          "Pause without shrugging, then return under control.",
        ],
      },
      {
        id: "c-leg-press",
        name: "Leg press",
        sets: 2,
        reps: "10–12 reps",
        rest: 120,
        effort: "3 reps in reserve",
        instructions: [
          "Reuse your recorded Session B setup.",
          "Keep hips down and knees tracking with toes.",
        ],
      },
      {
        id: "c-leg-curl",
        name: "Seated or lying leg curl",
        sets: 2,
        reps: "10–15 reps",
        rest: 90,
        effort: "2–3 reps in reserve",
        instructions: [
          "Align the knee with the pivot and keep hips planted.",
          "Curl smoothly without bouncing the stack.",
        ],
      },
      {
        id: "c-reverse-pec",
        name: "Reverse pec-deck",
        sets: 2,
        reps: "12–15 reps",
        rest: 60,
        effort: "Very light, 3 reps in reserve",
        instructions: [
          "Set the handles so the arms begin slightly in front of the body.",
          "Keep chest supported and move the upper arms outward without shrugging.",
        ],
        caution: "Optional: skip it if you cannot identify or set up the machine confidently.",
      },
      {
        id: "c-crunch",
        name: "Reverse crunch or crunch machine",
        sets: 2,
        reps: "8–15 reps",
        rest: 60,
        effort: "2–3 reps in reserve",
        instructions: [
          "Curl the pelvis or ribs under control rather than swinging.",
          "Keep the neck relaxed and finish each repetition slowly.",
        ],
        caution: "This strengthens abs; it does not selectively remove belly fat.",
      },
      {
        id: "c-cardio",
        name: "Pain-free cardio",
        sets: 1,
        reps: "10 min",
        rest: 0,
        effort: "Conversational pace",
        instructions: [
          "Walk, cycle or use the elliptical at a moderate effort.",
        ],
      },
    ],
  },
  {
    id: "D",
    title: "Optional upper + calisthenics",
    shortTitle: "Skill upper",
    subtitle: "Extra practice only after recovery",
    duration: "45–55 min",
    tone: "butter",
    image: "/assets/workout-upper.webp",
    summary: "A fourth-day skill session for weeks when soreness, sleep and joints are all good.",
    exercises: [
      { id: "d-pushup", name: "Incline push-up", sets: 3, reps: "5–10 reps", rest: 75, effort: "3 reps in reserve", instructions: ["Use the same straight-body setup as Session A.", "Lower the bench only after clean sets are consistent."], caution: "Never test floor push-ups every workout." },
      { id: "d-pullup", name: "Assisted pull-up or chin-up", sets: 3, reps: "4–6 reps", rest: 120, effort: "2–3 reps in reserve", instructions: ["Use controlled assistance and no kicking.", "Reduce assistance only after repeatable clean sets." ] },
      { id: "d-row", name: "Seated row", sets: 2, reps: "10–12 reps", rest: 90, effort: "2–3 reps in reserve", instructions: ["Keep the torso still and shoulders down.", "Pause briefly with elbows beside the body." ] },
      { id: "d-triceps", name: "Rope triceps pressdown", sets: 2, reps: "12–15 reps", rest: 60, effort: "2–3 reps in reserve", instructions: ["Keep elbows beside your ribs.", "Move only the forearms." ] },
      { id: "d-curl", name: "Dumbbell or cable curl", sets: 2, reps: "12–15 reps", rest: 60, effort: "2–3 reps in reserve", instructions: ["Keep elbows quiet and lower slowly.", "Choose a load that needs no body swing." ] },
      { id: "d-raise", name: "Machine or cable lateral raise", sets: 1, reps: "12–15 reps", rest: 60, effort: "3 reps in reserve", instructions: ["Stay light and stop around shoulder height."], caution: "Skip immediately if the shoulder joint hurts." },
      { id: "d-compression", name: "Seated single-leg compression", sets: 2, reps: "6–10 / side", rest: 60, effort: "Controlled", instructions: ["Sit tall and lift one straight heel without leaning back.", "Alternate sides." ] },
      { id: "d-cardio", name: "Easy cardio", sets: 1, reps: "8–10 min", rest: 0, effort: "Easy to moderate", instructions: ["Keep it easy enough that this optional day does not reduce recovery." ] },
    ],
  },
  {
    id: "E",
    title: "Optional conditioning + trunk",
    shortTitle: "Conditioning",
    subtitle: "Low-stress movement and stability",
    duration: "35–45 min",
    tone: "sage",
    image: "/assets/workout-lower.webp",
    summary: "A fifth visit that should leave you fresher—not exhausted.",
    exercises: [
      { id: "e-cardio", name: "Walk, bike or elliptical", sets: 1, reps: "5 easy + 20–25 moderate", rest: 0, effort: "Full sentences possible", instructions: ["Build the first five minutes gradually.", "Use a hands-free treadmill speed or choose a low-impact machine."], caution: "No running until the shin return gate is complete." },
      { id: "e-bridge", name: "Glute bridge", sets: 2, reps: "12–15 reps", rest: 60, effort: "3 reps in reserve", instructions: ["Keep ribs down and squeeze the glutes.", "Stop before the lower back arches." ] },
      { id: "e-calf", name: "Calf raise", sets: 2, reps: "12–15 reps", rest: 60, effort: "2–3 reps in reserve", instructions: ["Move through a comfortable range without bouncing." ] },
      { id: "e-tibialis", name: "Tibialis raise", sets: 2, reps: "15–20 reps", rest: 45, effort: "3 reps in reserve", instructions: ["Keep heels down and lift the forefoot."], caution: "Omit if shin-bone symptoms appear." },
      { id: "e-side-plank", name: "Side plank", sets: 2, reps: "15–25 sec / side", rest: 60, effort: "Clean position", instructions: ["Stack shoulder over elbow and keep hips lifted.", "Stop before the torso rotates or sags." ] },
    ],
  },
];

export const foodCategories = [
  { id: "all", label: "All food" },
  { id: "no-cook", label: "No cook" },
  { id: "pan", label: "Pan recipes" },
  { id: "produce", label: "Fruit + veg" },
  { id: "outside", label: "Outside" },
  { id: "limit", label: "Limit" },
];

export const foods = [
  {
    id: "whey-banana",
    name: "Whey + banana",
    category: "no-cook",
    serving: "1 scoop whey + 1 banana",
    calories: 250,
    protein: 25,
    time: "2 min",
    ingredients: ["1 product-label whey serving", "250–300 ml water", "1 banana"],
    howTo: ["Shake whey with water until smooth.", "Eat the banana separately; do not add biscuits or syrup."],
    note: "A bridge or protein add-on—not a complete day or full dinner.",
  },
  {
    id: "milk-chana-fruit",
    name: "UHT milk, chana + fruit",
    category: "no-cook",
    serving: "250 ml milk + 50 g chana + 1 fruit",
    calories: 410,
    protein: 18,
    time: "1 min",
    ingredients: ["1 unopened UHT milk pack", "1 closed fist roasted chana", "Banana, guava or orange"],
    howTo: ["Open the milk only when ready to finish it; without refrigeration, discard it after two hours—or one hour above 32°C.", "Measure one fist of chana rather than eating from a large bag."],
    note: "Shelf-stable until opened and useful after college.",
  },
  {
    id: "oats-whey",
    name: "Oats + whey shaker",
    category: "no-cook",
    serving: "50 g oats + 1 scoop whey",
    calories: 310,
    protein: 29,
    time: "5 min",
    ingredients: ["50 g plain oats", "1 product-label whey serving", "300–400 ml water"],
    howTo: ["Blend or shake oats and whey with water.", "Let it sit five minutes if the raw-oat texture feels rough."],
    note: "Use the whey label for the actual totals. This is useful when normal food leaves protein short; no sugary granola needed.",
  },
  {
    id: "chana-guava",
    name: "Roasted chana + guava",
    category: "no-cook",
    serving: "50 g chana + 1 guava",
    calories: 280,
    protein: 12,
    time: "1 min",
    ingredients: ["1 closed fist roasted chana", "1 washed guava"],
    howTo: ["Portion the chana before eating.", "Wash and eat the guava whole or sliced."],
    note: "Cheap fibre and some protein, but not a complete protein anchor by itself.",
  },
  {
    id: "fruit-peanuts",
    name: "Fruit + measured peanuts",
    category: "no-cook",
    serving: "1 fruit + 25 g peanuts",
    calories: 250,
    protein: 7,
    time: "1 min",
    ingredients: ["Apple, banana, guava or orange", "1 small measured handful peanuts"],
    howTo: ["Keep peanuts to one small handful.", "Eat with a whole fruit rather than juice."],
    note: "Nutritious and portable; peanuts are calorie-dense, not unlimited protein.",
  },
  {
    id: "soy-masala-roti",
    name: "Quick soy masala + rotis",
    category: "pan",
    serving: "50 g dry soy + 2 rotis",
    calories: 500,
    protein: 34,
    time: "15 min",
    ingredients: ["50 g dry soy chunks", "2 rotis", "Onion or tomato if available", "Chilli, turmeric, salt", "1 tsp oil"],
    howTo: ["Boil soy chunks until soft, drain and squeeze out water.", "Pan-cook onion/tomato and spices in one teaspoon oil.", "Add soy, splash in water and cook for 4–5 minutes. Eat immediately."],
    note: "One of the cheapest high-protein evening anchors.",
  },
  {
    id: "egg-bhurji",
    name: "Three-egg bhurji + rotis",
    category: "pan",
    serving: "3 eggs + 2 rotis",
    calories: 520,
    protein: 27,
    time: "10 min",
    ingredients: ["3 eggs", "2 rotis", "Onion/tomato optional", "Salt, pepper or chilli", "1 tsp oil"],
    howTo: ["Beat eggs with seasoning.", "Cook vegetables briefly in oil, add eggs and stir until fully set.", "Eat immediately with rotis; without refrigeration, discard leftovers after two hours—or one hour above 32°C."],
    note: "Optional for days you are willing to cook; boiled eggs are not required.",
  },
  {
    id: "paneer-pepper",
    name: "Paneer pepper toss",
    category: "pan",
    serving: "150 g paneer + 2 rotis",
    calories: 680,
    protein: 35,
    time: "12 min",
    ingredients: ["150 g paneer bought the same day", "2 rotis", "Pepper, chilli, salt", "Onion/capsicum optional", "1 tsp oil"],
    howTo: ["Cube the paneer and pan-brown lightly with seasoning.", "Add vegetables and cook until just soft.", "Eat immediately; without refrigeration, discard leftovers after two hours—or one hour above 32°C."],
    note: "Higher calorie than chicken or soy, so keep the oil measured.",
  },
  {
    id: "pepper-chicken",
    name: "One-pan pepper chicken",
    category: "pan",
    serving: "150 g cooked chicken + 2 rotis",
    calories: 640,
    protein: 50,
    time: "20 min",
    ingredients: ["About 200 g raw boneless chicken bought the same day", "2 rotis", "Pepper, chilli, turmeric, salt", "Onion optional", "1 tsp oil"],
    howTo: ["Buy the chicken only when you can cook it immediately; keep it separate from produce and use clean utensils.", "Cook the thickest piece to 74°C using a food thermometer. Colour alone is not a safe test.", "Eat immediately. Without refrigeration, discard leftovers after two hours—or one hour above 32°C—and clean hands, board, knife and pan."],
    note: "Strong protein anchor. If you cannot verify safe storage and 74°C cooking, choose freshly cooked PG or restaurant chicken instead.",
  },
  {
    id: "banana",
    name: "Banana",
    category: "produce",
    serving: "1 medium banana",
    calories: 105,
    protein: 1,
    time: "Ready",
    ingredients: ["1 banana"],
    howTo: ["Eat whole. Pair with whey, milk or chana when it needs to hold you longer."],
    note: "Convenient carbohydrate around training; it is not a protein source.",
  },
  {
    id: "guava",
    name: "Guava",
    category: "produce",
    serving: "1 medium guava",
    calories: 90,
    protein: 3,
    time: "Ready",
    ingredients: ["1 washed guava"],
    howTo: ["Eat whole or slice just before eating."],
    note: "High-fibre whole fruit; much better than packaged juice for fullness.",
  },
  {
    id: "orange-apple",
    name: "Orange or apple",
    category: "produce",
    serving: "1 medium fruit",
    calories: 85,
    protein: 1,
    time: "Ready",
    ingredients: ["1 orange or apple"],
    howTo: ["Wash and eat whole rather than drinking juice."],
    note: "Portable fibre and micronutrients; pair with a protein item.",
  },
  {
    id: "crunch-veg",
    name: "Cucumber + carrot plate",
    category: "produce",
    serving: "1 cucumber + 1 carrot",
    calories: 90,
    protein: 2,
    time: "4 min",
    ingredients: ["1 cucumber", "1 carrot", "Lemon, pepper and a little salt optional"],
    howTo: ["Wash thoroughly and cut just before eating.", "Add lemon and pepper; avoid turning it into a mayonnaise salad."],
    note: "Adds volume and fibre but is not a meal by itself.",
  },
  {
    id: "papaya",
    name: "Papaya bowl",
    category: "produce",
    serving: "1 medium bowl",
    calories: 95,
    protein: 1,
    time: "3 min",
    ingredients: ["1 bowl fresh papaya"],
    howTo: ["Buy a small fresh portion and eat it promptly. Without refrigeration, discard cut fruit after two hours—or one hour above 32°C."],
    note: "Easy fruit option; whole uncut fruit is safer to keep in the room.",
  },
  {
    id: "grilled-chicken-roti",
    name: "Grilled chicken + rotis",
    category: "outside",
    serving: "150–200 g chicken + 2 rotis + veg",
    calories: 720,
    protein: 55,
    time: "Order",
    ingredients: ["Grilled or tandoori chicken", "2 plain rotis", "Vegetables or salad"],
    howTo: ["Order one main only.", "Limit mayonnaise, skip fries and a calorie drink.", "Use this as the main dinner, not a starter before another large meal."],
    note: "Best outside protein anchor when the portion is not soaked in butter or cream.",
  },
  {
    id: "tikka-roti",
    name: "Chicken tikka + rotis",
    category: "outside",
    serving: "6–8 pieces + 2 rotis",
    calories: 660,
    protein: 48,
    time: "Order",
    ingredients: ["6–8 chicken tikka pieces", "2 plain rotis", "Vegetables or salad"],
    howTo: ["Choose tikka rather than fried starters.", "Order no second main, fries, dessert or milkshake."],
    note: "Restaurant oil varies; treat the energy estimate as approximate.",
  },
  {
    id: "dal-sabzi-roti",
    name: "Dal, sabzi + rotis",
    category: "outside",
    serving: "2 bowls dal + sabzi + 2 rotis",
    calories: 650,
    protein: 25,
    time: "Order",
    ingredients: ["2 bowls thick dal", "1 bowl vegetables", "2 plain rotis"],
    howTo: ["Ask for thick dal when possible.", "Skip butter topping and fried sides."],
    note: "Balanced vegetarian order, though protein remains below a chicken anchor.",
  },
  {
    id: "idli-sambar",
    name: "Idli + extra sambar",
    category: "outside",
    serving: "3 idlis + 2 bowls sambar",
    calories: 470,
    protein: 16,
    time: "Order",
    ingredients: ["3 idlis", "2 bowls sambar"],
    howTo: ["Use extra sambar for more fullness and pulses.", "Skip vada and sugary drinks."],
    note: "A lighter outside option; add a separate protein source later.",
  },
  {
    id: "biryani",
    name: "Chicken biryani",
    category: "limit",
    serving: "1 mini/single, about 350–450 g",
    calories: 800,
    protein: 28,
    time: "Delivery treat: ≤1/week total",
    ingredients: ["One mini or single biryani"],
    howTo: ["No second serving, starter, dessert or calorie drink.", "Share or discard restaurant excess rather than saving it at room temperature."],
    note: "Counts as the one weekly delivery-treat occasion across biryani, shawarma, burger, pizza or fried chicken.",
  },
  {
    id: "shawarma",
    name: "Chicken shawarma",
    category: "limit",
    serving: "1 regular roll",
    calories: 620,
    protein: 27,
    time: "Delivery treat: ≤1/week total",
    ingredients: ["One regular chicken shawarma roll"],
    howTo: ["Choose regular—not plate, jumbo or double.", "No cheese, fries or extra mayonnaise."],
    note: "Counts as the one weekly delivery-treat occasion; never two rolls or two plates.",
  },
  {
    id: "burger",
    name: "Single chicken burger",
    category: "limit",
    serving: "1 single-patty burger",
    calories: 560,
    protein: 24,
    time: "Delivery treat: ≤1/week total",
    ingredients: ["One single-patty burger"],
    howTo: ["Order the burger alone.", "No second burger, fries, dessert or drink."],
    note: "Counts as the one weekly delivery-treat occasion.",
  },
  {
    id: "chicken-strips",
    name: "Chicken strips",
    category: "limit",
    serving: "Maximum 3 strips",
    calories: 460,
    protein: 29,
    time: "Delivery treat: ≤1/week total",
    ingredients: ["Three chicken strips"],
    howTo: ["Stop at three strips.", "No bucket, fries, creamy dip or calorie drink."],
    note: "Counts as the one weekly delivery-treat occasion. Protein does not cancel easy over-ordering.",
  },
  {
    id: "pizza",
    name: "Regular chicken pizza",
    category: "limit",
    serving: "2 regular slices",
    calories: 600,
    protein: 26,
    time: "Delivery treat: ≤1/week total",
    ingredients: ["Two regular-crust chicken pizza slices"],
    howTo: ["Choose regular crust—not cheese-burst or stuffed crust.", "Order no sides, dessert or calorie drink. Use the restaurant nutrition label when available."],
    note: "Counts as the one weekly delivery-treat occasion. The displayed nutrition is a rough midpoint.",
  },
  {
    id: "cake",
    name: "Cake or cake jar",
    category: "limit",
    serving: "80–100 g small piece",
    calories: 350,
    protein: 4,
    time: "Sweet treats: ≤2/month total",
    ingredients: ["One small cake portion"],
    howTo: ["Eat after a real meal, not as dinner.", "Never order a jar plus another cake."],
    note: "An optional four-week pause can break the habit; afterward, cake and milkshakes share two small occasions per month.",
  },
  {
    id: "milkshake",
    name: "Milkshake",
    category: "limit",
    serving: "200–250 ml small shake",
    calories: 430,
    protein: 9,
    time: "Sweet treats: ≤2/month total",
    ingredients: ["One small plain shake"],
    howTo: ["No Oreo, ice-cream scoop or toppings.", "It replaces dessert; it does not accompany one."],
    note: "An optional four-week pause can break the habit; afterward, cake and milkshakes share two small occasions per month.",
  },
  {
    id: "chips",
    name: "Chips or Kurkure",
    category: "limit",
    serving: "25–30 g single pack",
    calories: 165,
    protein: 2,
    time: "Packaged snack: ≤1/week",
    ingredients: ["One single-serve packet"],
    howTo: ["Buy only the single portion when using the token.", "Do not keep family bags or bulk snack stock in the room."],
    note: "Buy a single portion only. The environment rule matters more than pretending the snack is forbidden forever.",
  },
];
