export const FOOD_REFERENCE = {
  energyKcal: 2000,
  proteinGrams: 110,
};

export const FOOD_CATEGORIES = [
  { id: "all", label: "All choices" },
  { id: "no-cook", label: "Mix + eat" },
  { id: "pan", label: "Pan recipes" },
  { id: "produce", label: "Fruit + veg" },
  { id: "protein", label: "Protein add-ons" },
  { id: "limit", label: "Limit / avoid" },
];

export const FOOD_FAMILY_GUIDES = [
  {
    id: "plain-staple-base",
    lane: "choose",
    title: "Plain staple base",
    examples: "Rice, rotis, idli, idiyappam, pongal or upma",
    guidance: "Start with one ordinary PG or packet portion. Add a protein source and produce when they are available instead of ordering a second starch-heavy main.",
  },
  {
    id: "protein-anchor",
    lane: "choose",
    title: "Protein anchor",
    examples: "Chicken, eggs, paneer, soy, dal, chana, sattu or whey",
    guidance: "Choose one practical protein source rather than waiting for a perfect meal. Whey can fill a gap, but it does not replace fruit, vegetables or ordinary food.",
  },
  {
    id: "whole-produce",
    lane: "choose",
    title: "Whole fruit + vegetables",
    examples: "Banana, guava, orange, apple, cucumber, carrot or tomato",
    guidance: "Buy whole produce or a single fresh-cut serving. It adds fibre and volume; it is usually a side or snack, not a protein-rich meal by itself.",
  },
  {
    id: "shelf-stable-bridge",
    lane: "choose",
    title: "Shelf-stable bridge",
    examples: "Roasted chana, sattu, oats, soy chunks, UHT milk or whey",
    guidance: "Keep dry foods sealed and portion them into a bowl before eating. Use small UHT packs because an opened pack cannot sit safely in a warm room.",
  },
  {
    id: "simple-drinks",
    lane: "choose",
    title: "Drinks that stay simple",
    examples: "Water, plain UHT milk, sattu water or whey with water",
    guidance: "Use drinks for hydration or a specific protein gap. Whole fruit is generally more filling than juice, and cafe shakes belong with desserts rather than hydration.",
  },
  {
    id: "double-main-orders",
    lane: "limit",
    title: "Double-main orders",
    examples: "Two burgers, two shawarmas, biryani plus a starter",
    guidance: "Choose one main. A second main is the easiest part of the order to remove without turning the occasion into a restrictive or joyless meal.",
  },
  {
    id: "fried-combos",
    lane: "limit",
    title: "Fried combo meals",
    examples: "Burger + fries, wrap + tenders, fried rice + chilli chicken",
    guidance: "Pick the item you actually want and leave out the automatic fried side and sweet drink. Combo pricing does not make the full combo a useful portion.",
  },
  {
    id: "dessert-as-dinner",
    lane: "limit",
    title: "Dessert replacing food",
    examples: "Cake jar, dream-cake tub, ice-cream tub",
    guidance: "Do not use dessert as the only dinner. If you want one, have a small single portion after ordinary food instead of ordering several desserts while very hungry.",
  },
  {
    id: "liquid-desserts",
    lane: "limit",
    title: "Liquid desserts",
    examples: "Oreo shake, syrup milkshake, large soft drink",
    guidance: "Treat these as the occasional sweet item, not as hydration and not as a free add-on. Water can remain the default drink with delivery food.",
  },
  {
    id: "bulk-room-snacks",
    lane: "limit",
    title: "Bulk room snacks",
    examples: "Large chips, biscuit sleeves, chocolate bars or multipacks",
    guidance: "The room supply matters more than willpower. Buy the smallest single portion, place it in a bowl and avoid keeping backup packs beside the desk.",
  },
];

export const FOOD_ITEMS = [
  {
    id: "banana-oat-shake",
    category: "no-cook",
    name: "Chocolate banana oat shake",
    strap: "Sweet, filling and easy to blend without protein powder.",
    portion: "1 banana + 30 g oats + 250 ml UHT milk + 1 tsp cocoa",
    kcal: [340, 430],
    protein: [12, 17],
    prep: "4 min",
    tags: ["Blender", "Sweet"],
    ingredients: ["1 banana", "3 heaped tbsp dry oats", "1 small 250 ml UHT milk carton", "1 tsp unsweetened cocoa", "Water or ice only if available safely"],
    steps: ["Blend until smooth.", "Add water if it is too thick.", "Drink immediately; do not keep an opened milk shake in the room."],
    note: "This is a substantial snack or small meal, not a zero-calorie drink. The milk brand and banana size change the estimate.",
  },
  {
    id: "peanut-banana-roti",
    category: "no-cook",
    name: "Peanut-banana roti roll",
    strap: "A sweet wrap that is more satisfying than biscuits or cake.",
    portion: "2 medium rotis + 1 banana + 1 level tbsp peanut butter",
    kcal: [430, 540],
    protein: [12, 17],
    prep: "3 min",
    tags: ["No fridge", "Sweet"],
    ingredients: ["2 fresh medium rotis", "1 banana", "1 level tbsp peanut butter", "Pinch of cinnamon, optional"],
    steps: ["Spread the peanut butter thinly across both rotis.", "Split the banana between them, roll and eat.", "Keep the peanut butter layer measured; extra spoonfuls add up quickly."],
    note: "Useful when a proper lunch is not available, but it is not especially high in protein by itself.",
  },
  {
    id: "spicy-chana-bhel",
    category: "no-cook",
    name: "Spicy roasted-chana bhel",
    strap: "Crunchy, salty and fresh without opening a chips packet.",
    portion: "50 g roasted chana + cucumber + tomato + lemon",
    kcal: [220, 300],
    protein: [10, 14],
    prep: "6 min",
    tags: ["No fridge", "Savoury"],
    ingredients: ["2 small handfuls roasted chana, about 50 g", "1/2 cucumber", "1 small tomato", "Lemon", "Chilli powder, pepper or chaat masala"],
    steps: ["Chop the cucumber and tomato.", "Mix with roasted chana, lemon and a light dusting of spice.", "Eat immediately so the chana stays crunchy."],
    note: "Choose plain roasted chana when possible. Salted versions can be much higher in sodium.",
  },
  {
    id: "apple-cinnamon-oats",
    category: "no-cook",
    name: "Apple-cinnamon oat cup",
    strap: "Cool, lightly sweet oats with crunch and no cooking.",
    portion: "40 g oats + 250 ml UHT milk + 1 small apple",
    kcal: [330, 420],
    protein: [12, 17],
    prep: "5 min",
    tags: ["Mix + eat", "Sweet"],
    ingredients: ["4 heaped tbsp oats, about 40 g", "1 small UHT milk carton", "1 small chopped apple", "Cinnamon, optional"],
    steps: ["Mix the oats and milk in a bowl.", "Top with chopped apple and cinnamon.", "Eat immediately rather than soaking it in an unrefrigerated room."],
    note: "Use unsweetened oats or muesli. Sweetened granola can make the same bowl much more energy-dense.",
  },
  {
    id: "sattu-lemon-drink",
    category: "no-cook",
    name: "Savoury sattu drink",
    strap: "A budget-friendly drink with more substance than juice.",
    portion: "40 g sattu + 300 ml water + lemon",
    kcal: [140, 190],
    protein: [8, 11],
    prep: "3 min",
    tags: ["Shelf-stable", "Budget"],
    ingredients: ["4 level tbsp sattu, about 40 g", "300 ml safe drinking water", "Lemon", "Pinch of salt, cumin and chilli, optional"],
    steps: ["Mix sattu with a splash of water into a smooth paste.", "Add the remaining water and season lightly.", "Stir again before drinking."],
    note: "This can bridge a long food gap, but it is not a complete replacement for a proper meal.",
  },
  {
    id: "paneer-cucumber-chaat",
    category: "no-cook",
    name: "Paneer cucumber chaat",
    strap: "Fresh, tangy and protein-forward when paneer is available nearby.",
    portion: "100 g paneer + 1/2 cucumber + lemon and spice",
    kcal: [280, 380],
    protein: [18, 23],
    prep: "5 min",
    tags: ["Eat now", "High protein"],
    ingredients: ["One fresh sealed 100 g paneer pack", "1/2 cucumber", "Lemon", "Pepper or chaat masala"],
    steps: ["Buy the paneer immediately before eating.", "Cube it and mix with chopped cucumber, lemon and spice.", "Finish the whole prepared portion promptly."],
    note: "Paneer is perishable. With no refrigerator, do not buy it early, save leftovers or keep an opened pack for later.",
  },
  {
    id: "curd-chana-crunch",
    category: "no-cook",
    name: "Curd chana crunch",
    strap: "A cool savoury bowl; optional if you dislike plain curd.",
    portion: "200 g single-serve curd + 40 g roasted chana + cucumber",
    kcal: [260, 360],
    protein: [14, 20],
    prep: "4 min",
    tags: ["Eat now", "Optional"],
    ingredients: ["1 sealed 200 g plain-curd cup", "40 g roasted chana", "1/2 cucumber", "Cumin, pepper and salt"],
    steps: ["Open the curd only when ready to eat.", "Mix in chopped cucumber and seasoning.", "Add chana last for crunch and finish immediately."],
    note: "This is included as an optional flavour variation, not something you need to force yourself to eat.",
  },
  {
    id: "chana-peanut-mix",
    category: "no-cook",
    name: "Chana-peanut crunch cup",
    strap: "A portable dry mix with a clear portion boundary.",
    portion: "40 g roasted chana + 20 g peanuts",
    kcal: [270, 330],
    protein: [13, 17],
    prep: "1 min",
    tags: ["Shelf-stable", "Portable"],
    ingredients: ["About 1.5 small handfuls roasted chana", "About 1 small cupped handful peanuts", "Chilli powder or pepper, optional"],
    steps: ["Measure both into a small bowl or container.", "Season lightly and close the larger packets before eating.", "Stop at the prepared cup instead of eating from the packet."],
    note: "Nut calories rise quickly when eaten straight from a large bag, so portioning first matters.",
  },
  {
    id: "masala-scrambled-eggs",
    category: "pan",
    name: "Masala scrambled eggs",
    strap: "Soft eggs with onion, tomato and spice in one pan.",
    portion: "2 eggs + onion and tomato + 1 tsp oil",
    kcal: [210, 290],
    protein: [13, 17],
    prep: "10 min",
    tags: ["Beginner", "One pan"],
    ingredients: ["2 eggs", "1/4 onion", "1/2 tomato", "1 tsp oil", "Salt, pepper and chilli"],
    steps: ["Heat the oil on medium and soften the chopped onion and tomato.", "Beat in the eggs and stir gently.", "Cook until no wet egg remains, then eat promptly."],
    note: "Add one or two rotis separately if you need a larger meal; include their package or PG estimate when comparing.",
  },
  {
    id: "pepper-chicken-pan",
    category: "pan",
    name: "Pepper chicken quick toss",
    strap: "Simple juicy chicken with vegetables and no heavy restaurant gravy.",
    portion: "150 g cooked boneless chicken + vegetables + 1–2 tsp oil",
    kcal: [320, 450],
    protein: [40, 50],
    prep: "18 min",
    tags: ["High protein", "One pan"],
    ingredients: ["Enough raw boneless chicken to yield about 150 g cooked", "1 cup sliced onion, capsicum or carrot", "1–2 tsp oil", "Pepper, chilli, turmeric and salt"],
    steps: ["Buy raw chicken immediately before cooking and keep it separate from ready-to-eat food.", "Cook the chicken pieces over medium heat, turning until fully cooked throughout.", "Add vegetables and seasoning; toss until tender-crisp. Wash hands, board and knife after raw chicken contact."],
    note: "Chicken size and oil cause most of the range. If you can check temperature, the thickest piece should reach 74°C; otherwise cut the thickest piece to confirm it is steaming and not pink or translucent.",
  },
  {
    id: "soy-masala-toss",
    category: "pan",
    name: "Soy-chunk masala toss",
    strap: "A shelf-stable, budget protein option with bold flavour.",
    portion: "50 g dry soy chunks + onion and tomato + 1 tsp oil",
    kcal: [250, 340],
    protein: [25, 30],
    prep: "18 min",
    tags: ["Budget", "Shelf-stable"],
    ingredients: ["50 g dry soy chunks", "1/2 onion", "1 tomato", "1 tsp oil", "Chilli, turmeric, garam masala and salt"],
    steps: ["Boil or simmer the soy chunks in water until soft, following the pack.", "Drain, cool enough to handle and squeeze out excess water.", "Pan-toss onion and tomato with oil and spices, then add soy for 3–4 minutes."],
    note: "The estimate is for the soy mixture, not rice or rotis served with it.",
  },
  {
    id: "paneer-pepper-toss",
    category: "pan",
    name: "Paneer pepper toss",
    strap: "Golden paneer and vegetables with a dry, punchy masala.",
    portion: "150 g paneer + vegetables + 1 tsp oil",
    kcal: [430, 560],
    protein: [27, 34],
    prep: "14 min",
    tags: ["Vegetarian", "Eat now"],
    ingredients: ["150 g fresh paneer", "1 cup onion, tomato or capsicum", "1 tsp oil", "Pepper, chilli and garam masala"],
    steps: ["Buy paneer close to cooking time and cut it into cubes.", "Brown it lightly in oil, then add the chopped vegetables.", "Season, cook until the vegetables soften and eat immediately."],
    note: "Paneer is nutritious but energy-dense; more oil or a larger block quickly moves the portion above this range.",
  },
  {
    id: "besan-chilla",
    category: "pan",
    name: "Two vegetable besan chillas",
    strap: "Crisp-edged savoury pancakes made from shelf-stable flour.",
    portion: "70 g besan batter + vegetables + 2 tsp oil total",
    kcal: [330, 440],
    protein: [15, 20],
    prep: "16 min",
    tags: ["Budget", "Vegetarian"],
    ingredients: ["About 3/4 cup besan, 70 g", "Water", "Chopped onion or tomato", "2 tsp oil across both chillas", "Chilli, cumin and salt"],
    steps: ["Whisk besan, water, vegetables and seasoning into a pourable batter.", "Use half the oil for each chilla in a medium-hot pan.", "Cook both sides until set and golden with no wet batter inside."],
    note: "The oil amount matters. Pour it with a teaspoon rather than straight from the bottle.",
  },
  {
    id: "egg-roti-roll",
    category: "pan",
    name: "Double egg roti roll",
    strap: "A filling, portable option made from two familiar basics.",
    portion: "2 eggs + 2 medium rotis + onion + 1 tsp oil",
    kcal: [430, 560],
    protein: [20, 26],
    prep: "12 min",
    tags: ["Filling", "Portable"],
    ingredients: ["2 eggs", "2 medium rotis", "Sliced onion", "1 tsp oil", "Pepper, chilli and salt"],
    steps: ["Scramble or make a thin omelette with the measured oil.", "Divide it between the rotis and add onion and spice.", "Roll tightly and eat while fresh."],
    note: "This is the complete two-roll portion; mayonnaise and cheese are not included in the estimate.",
  },
  {
    id: "oats-egg-chilla",
    category: "pan",
    name: "Oats egg chilla",
    strap: "A thick savoury pancake with more staying power than plain eggs.",
    portion: "2 eggs + 40 g oats + vegetables + 1 tsp oil",
    kcal: [340, 430],
    protein: [20, 25],
    prep: "14 min",
    tags: ["One pan", "High protein"],
    ingredients: ["2 eggs", "4 heaped tbsp oats, about 40 g", "Chopped onion or tomato", "1 tsp oil", "Pepper, chilli and salt"],
    steps: ["Blend or crush the oats, then mix with eggs, vegetables and seasoning.", "Pour into a lightly oiled pan over medium-low heat.", "Cook both sides until the egg is fully set."],
    note: "If the chilla breaks, make two smaller ones instead of adding more oil.",
  },
  {
    id: "soy-masala-oats",
    category: "pan",
    name: "Masala oats with soy",
    strap: "A warm bowl that combines carbs, vegetables and protein.",
    portion: "40 g oats + 30 g dry soy chunks + vegetables + 1 tsp oil",
    kcal: [300, 400],
    protein: [20, 25],
    prep: "18 min",
    tags: ["One pan", "Shelf-stable"],
    ingredients: ["40 g oats", "30 g dry soy chunks", "1 cup chopped vegetables", "1 tsp oil", "Chilli, turmeric and salt"],
    steps: ["Soften the soy chunks in hot water according to the pack, then drain and squeeze.", "Cook vegetables and spices briefly in the measured oil.", "Add oats, soy and water; simmer until thick and fully hot."],
    note: "Instant flavoured oats can have different calories and much more sodium; check the pack if using them.",
  },
  {
    id: "banana",
    category: "produce",
    name: "Banana",
    strap: "Portable, inexpensive and useful before a late workout.",
    portion: "1 medium banana",
    kcal: [90, 120],
    protein: [1, 2],
    prep: "Peel",
    tags: ["Portable", "Pre-workout"],
    ingredients: ["1 medium banana"],
    steps: ["Peel and eat.", "Pair with a protein item when using it as more than a quick snack."],
    note: "Fruit supports the day; it is not a protein meal by itself.",
  },
  {
    id: "apple",
    category: "produce",
    name: "Apple",
    strap: "Crisp, portable and easy to keep uncut at room temperature.",
    portion: "1 small-to-medium apple",
    kcal: [70, 110],
    protein: [0, 1],
    prep: "Wash",
    tags: ["Portable", "No fridge"],
    ingredients: ["1 apple"],
    steps: ["Wash under safe running water.", "Eat whole; do not leave cut apple sitting in a hot room."],
    note: "Pair with roasted chana, milk or another protein add-on if hunger is substantial.",
  },
  {
    id: "orange",
    category: "produce",
    name: "Orange",
    strap: "Juicy whole fruit with more fullness than packaged juice.",
    portion: "1 medium orange",
    kcal: [55, 85],
    protein: [1, 2],
    prep: "Peel",
    tags: ["Whole fruit", "No fridge"],
    ingredients: ["1 medium orange"],
    steps: ["Wash the outside, peel and eat the segments.", "Choose the whole fruit instead of juice most of the time."],
    note: "Fruit size varies. A glass of sweetened juice is a different item with less fibre and often more energy.",
  },
  {
    id: "guava",
    category: "produce",
    name: "Guava",
    strap: "A filling Chennai-friendly fruit that needs no preparation beyond washing.",
    portion: "1 medium guava",
    kcal: [55, 100],
    protein: [2, 4],
    prep: "Wash + slice",
    tags: ["Local", "No fridge"],
    ingredients: ["1 medium guava"],
    steps: ["Wash thoroughly and cut with a clean knife.", "Eat immediately after cutting."],
    note: "The range accounts for the large size difference between guavas sold locally.",
  },
  {
    id: "papaya",
    category: "produce",
    name: "Papaya bowl",
    strap: "Soft, sweet fruit for when you can buy a ready single portion.",
    portion: "1 heaped bowl, about 250–300 g",
    kcal: [100, 150],
    protein: [1, 3],
    prep: "Eat now",
    tags: ["Fresh", "Single serve"],
    ingredients: ["One freshly cut single-serving papaya bowl"],
    steps: ["Buy from a clean, high-turnover shop.", "Eat promptly; do not save cut fruit without refrigeration."],
    note: "Avoid cut fruit that has been sitting warm or uncovered for an unknown time.",
  },
  {
    id: "cucumber-lime",
    category: "produce",
    name: "Cucumber lime plate",
    strap: "Crunchy volume beside a meal, not a meal replacement.",
    portion: "1 medium cucumber + lime and pepper",
    kcal: [25, 50],
    protein: [1, 2],
    prep: "4 min",
    tags: ["Fresh", "Savoury"],
    ingredients: ["1 medium cucumber", "Lime", "Pepper and a light pinch of salt"],
    steps: ["Wash and slice the cucumber.", "Season lightly and eat immediately."],
    note: "Use this to add crunch and volume beside protein and carbs; it cannot replace them.",
  },
  {
    id: "carrot-sticks",
    category: "produce",
    name: "Carrot sticks",
    strap: "A crisp snack or easy vegetable side.",
    portion: "2 medium carrots",
    kcal: [45, 80],
    protein: [1, 2],
    prep: "5 min",
    tags: ["Crunchy", "No cook"],
    ingredients: ["2 medium carrots", "Lemon or pepper, optional"],
    steps: ["Wash, peel if needed and cut with a clean knife.", "Eat soon after cutting."],
    note: "Add a protein item if this needs to hold you for more than a short period.",
  },
  {
    id: "tomato-cucumber-salad",
    category: "produce",
    name: "Tomato cucumber salad",
    strap: "A fresh, tangy side that makes a simple meal feel larger.",
    portion: "1 tomato + 1/2 cucumber + lemon",
    kcal: [35, 70],
    protein: [1, 3],
    prep: "6 min",
    tags: ["Side", "No cook"],
    ingredients: ["1 tomato", "1/2 cucumber", "Lemon", "Pepper or cumin"],
    steps: ["Wash and chop with a clean knife.", "Add lemon and seasoning just before eating."],
    note: "This estimate excludes oil, dressings and sev.",
  },
  {
    id: "whey-water",
    category: "protein",
    name: "Whey with water",
    strap: "A convenient protein gap-filler once you buy a verified product.",
    portion: "1 labelled scoop mixed with water",
    kcal: [120, 170],
    protein: [22, 25],
    prep: "1 min",
    tags: ["Future option", "Portable"],
    ingredients: ["1 scoop according to the product label", "Safe drinking water"],
    steps: ["Add water first, then one level labelled scoop.", "Shake, drink and wash the shaker promptly."],
    note: "Use the product label instead of this range when available. Whey is optional convenience, not a fat burner or a substitute for all meals.",
  },
  {
    id: "uht-milk",
    category: "protein",
    name: "Single-serve UHT milk",
    strap: "Shelf-stable while sealed and easy to combine with fruit or chana.",
    portion: "1 plain 250 ml carton",
    kcal: [120, 180],
    protein: [7, 9],
    prep: "Open + drink",
    tags: ["Sealed shelf-stable", "Drink now"],
    ingredients: ["1 plain unflavoured 250 ml UHT milk carton"],
    steps: ["Check the seal and best-before date.", "Open only when ready and finish the carton."],
    note: "Shelf-stable means unopened. Without a refrigerator, do not save an opened carton.",
  },
  {
    id: "roasted-chana",
    category: "protein",
    name: "Roasted chana",
    strap: "Cheap, portable and easier to portion than a mixed snack packet.",
    portion: "50 g, about 2 small handfuls",
    kcal: [180, 230],
    protein: [9, 12],
    prep: "Ready",
    tags: ["Budget", "Shelf-stable"],
    ingredients: ["50 g plain roasted chana"],
    steps: ["Measure into a bowl or small container.", "Reseal the main packet before eating."],
    note: "Keep the packet dry, tightly closed and away from heat, moisture and insects.",
  },
  {
    id: "soy-chunks",
    category: "protein",
    name: "Cooked soy chunks",
    strap: "One of the strongest low-cost protein choices in the index.",
    portion: "50 g dry weight, then boiled and squeezed",
    kcal: [170, 210],
    protein: [24, 28],
    prep: "12 min",
    tags: ["Budget", "Cook first"],
    ingredients: ["50 g dry soy chunks", "Water", "Salt or spice, optional"],
    steps: ["Cook according to the pack until fully soft.", "Drain and squeeze out excess water.", "Season and eat hot, or use in a pan recipe."],
    note: "The dry product stores well when sealed; cooked soy should be eaten promptly without refrigeration.",
  },
  {
    id: "fresh-paneer",
    category: "protein",
    name: "Fresh paneer",
    strap: "A useful vegetarian protein, but more energy-dense than chicken or whey.",
    portion: "100 g fresh paneer",
    kcal: [250, 340],
    protein: [17, 22],
    prep: "Eat or cook now",
    tags: ["Vegetarian", "Perishable"],
    ingredients: ["1 sealed 100 g paneer pack"],
    steps: ["Buy immediately before eating or cooking.", "Open, use the full portion and do not retain leftovers."],
    note: "Check the package label because paneer fat content varies considerably.",
  },
  {
    id: "two-eggs",
    category: "protein",
    name: "Two cooked eggs",
    strap: "An occasional compact protein add-on in the form you prefer.",
    portion: "2 eggs, scrambled or omelette, before added oil",
    kcal: [140, 180],
    protein: [12, 15],
    prep: "8 min",
    tags: ["Occasional", "Pan"],
    ingredients: ["2 eggs", "Seasoning"],
    steps: ["Crack into a clean bowl and discard any egg with an unusual smell.", "Cook until the white and yolk mixture is set.", "Add the oil used separately; one teaspoon contributes roughly another 40 kcal."],
    note: "This range does not include butter, cheese, mayonnaise or cooking oil.",
  },
  {
    id: "plain-chicken",
    category: "protein",
    name: "Plain cooked chicken",
    strap: "A high-protein base to add to rotis, rice or vegetables.",
    portion: "150 g cooked boneless chicken",
    kcal: [250, 340],
    protein: [40, 50],
    prep: "Cook fresh",
    tags: ["High protein", "Perishable"],
    ingredients: ["Enough fresh raw boneless chicken to yield about 150 g cooked", "Spices", "Up to 1 tsp oil if pan-cooking"],
    steps: ["Buy close to cooking time and prevent raw juices touching other food.", "Cook every piece fully; check the thickest piece before eating.", "Eat promptly and clean all raw-chicken contact surfaces."],
    note: "This estimate is for a lightly cooked portion, not restaurant gravy, breading or deep frying.",
  },
  {
    id: "dal-bowl",
    category: "protein",
    name: "Thick dal bowl",
    strap: "A familiar PG-friendly protein add-on when the dal is not mostly water.",
    portion: "1 full bowl, about 250 ml",
    kcal: [180, 300],
    protein: [9, 15],
    prep: "Serve hot",
    tags: ["PG friendly", "Variable"],
    ingredients: ["1 full bowl cooked dal"],
    steps: ["Choose a thick serving with visible lentils when possible.", "Treat rice, rotis and added ghee as separate portions."],
    note: "PG and restaurant recipes vary widely with water, oil and tempering, so this range is intentionally broad.",
  },
  {
    id: "sattu-portion",
    category: "protein",
    name: "Sattu portion",
    strap: "A shelf-stable roasted-gram powder for drinks or thick mixes.",
    portion: "40 g, about 4 level tbsp",
    kcal: [140, 190],
    protein: [8, 11],
    prep: "2 min",
    tags: ["Budget", "Shelf-stable"],
    ingredients: ["40 g sattu", "Water and seasoning"],
    steps: ["Mix with safe water into a drink or paste.", "Keep the dry bag tightly sealed after use."],
    note: "Protein differs by brand and whether other flour or sugar is mixed in; check the ingredient list.",
  },
  {
    id: "chicken-biryani",
    category: "limit",
    name: "Restaurant chicken biryani",
    strap: "Large rice, oil and chicken portions can cover a substantial part of the reference day.",
    portion: "1 regular restaurant box, no sides",
    kcal: [800, 1300],
    protein: [28, 50],
    prep: "Limit",
    tags: ["Weekly flex", "One box"],
    ingredients: ["One regular chicken biryani serving", "No starter, dessert or calorie drink in this comparison"],
    steps: ["Keep it to one regular box rather than a jumbo or second order.", "Skip the fried starter, sweet drink and dessert in the same occasion.", "Return to normal eating afterward; do not punish the meal with an all-day fast."],
    note: "Restaurant portions vary enormously. Use a posted nutrition label when one exists; this range is only orientation.",
  },
  {
    id: "shawarma-roll",
    category: "limit",
    name: "Chicken shawarma roll",
    strap: "The sauce, wrap size and added fries drive most of the variation.",
    portion: "1 regular roll",
    kcal: [500, 850],
    protein: [22, 40],
    prep: "Limit",
    tags: ["Weekly flex", "One roll"],
    ingredients: ["One regular chicken shawarma roll"],
    steps: ["Choose one roll, not two rolls or a plate plus burger.", "Ask for lighter sauce when practical.", "Do not add fries, dessert or a milkshake to the same order."],
    note: "A large plate shawarma can be much higher than this roll estimate.",
  },
  {
    id: "shawarma-plate",
    category: "limit",
    name: "Loaded shawarma plate",
    strap: "Bread, fries, sauces and a large meat pile make this difficult to estimate.",
    portion: "1 full restaurant plate",
    kcal: [750, 1200],
    protein: [30, 55],
    prep: "High impact",
    tags: ["Choose smaller", "No double"],
    comparable: false,
    ingredients: ["One loaded plate with meat, bread and sauces"],
    steps: ["Prefer a single regular roll when you want shawarma.", "If choosing the plate, make it the only ordered main.", "Never order two plates for one meal."],
    note: "This is a broad range because plate composition is inconsistent between shops.",
  },
  {
    id: "fried-chicken-strips",
    category: "limit",
    name: "Four fried chicken strips",
    strap: "Protein comes with breading and frying oil, especially with dips.",
    portion: "4 restaurant strips, before dips",
    kcal: [500, 850],
    protein: [30, 50],
    prep: "Limit",
    tags: ["No combo", "Skip dips"],
    ingredients: ["Four fried chicken strips"],
    steps: ["Keep the strips as the single ordered item.", "Skip fries, burger, dessert and sugary drink.", "Use the restaurant label if available."],
    note: "Breading thickness, strip size and dipping sauces can push the total beyond this range.",
  },
  {
    id: "double-burger",
    category: "limit",
    name: "Two chicken burgers",
    strap: "Your previous double-order pattern turns one treat into a very large meal.",
    portion: "2 restaurant chicken burgers",
    kcal: [950, 1500],
    protein: [35, 65],
    prep: "Avoid double",
    tags: ["Red flag", "Choose one"],
    ingredients: ["Two chicken burgers"],
    steps: ["Order one burger only if choosing it as the weekly flex.", "Do not add a second main because the first takes time to feel filling.", "Wait 20 minutes before deciding you need anything else."],
    note: "One burger is usually the simpler boundary. Exact values depend on patty, bun, cheese and sauce.",
  },
  {
    id: "burger-combo",
    category: "limit",
    name: "Burger, fries and drink combo",
    strap: "Three discretionary items bundled into one convenient order.",
    portion: "1 burger + medium fries + regular soft drink",
    kcal: [1000, 1600],
    protein: [25, 50],
    prep: "Avoid combo",
    tags: ["Swap to single", "Sugary drink"],
    ingredients: ["One burger", "One medium fries", "One regular sugary drink"],
    steps: ["Choose the burger alone if you want it.", "Use water instead of the drink.", "Do not replace the fries with dessert; simply remove the side."],
    note: "Restaurant labels are more useful than this broad range when available.",
  },
  {
    id: "pizza-four-slices",
    category: "limit",
    name: "Four pizza slices",
    strap: "Cheese, crust and toppings make a half-pizza portion energy-dense.",
    portion: "4 medium slices",
    kcal: [850, 1400],
    protein: [30, 55],
    prep: "Limit",
    tags: ["Weekly flex", "No sides"],
    ingredients: ["Four medium pizza slices"],
    steps: ["Order the smallest practical size or share it.", "Put the intended slices on a plate before eating.", "Skip garlic bread, dessert and sugary drink."],
    note: "Thin vegetable pizza and stuffed-crust meat pizza can sit at opposite ends of this range.",
  },
  {
    id: "fried-rice-chilli-chicken",
    category: "limit",
    name: "Fried rice + chilli chicken",
    strap: "Two oily restaurant mains combined into one order.",
    portion: "1 full fried-rice box + 1 chilli-chicken side",
    kcal: [1100, 1800],
    protein: [35, 70],
    prep: "Avoid combo",
    tags: ["Two mains", "High impact"],
    ingredients: ["One full fried rice", "One full chilli chicken side"],
    steps: ["Choose one main rather than both.", "If chicken is the priority, pair a smaller plain rice portion with a non-fried chicken dish when available.", "Avoid turning leftovers into a second unrefrigerated room meal."],
    note: "Oil, batter and restaurant portion size make the range especially uncertain.",
  },
  {
    id: "wrap-tenders",
    category: "limit",
    name: "Chicken wrap + four tenders",
    strap: "A wrap plus a second fried main repeats the double-order problem.",
    portion: "1 loaded wrap + 4 fried tenders",
    kcal: [1000, 1650],
    protein: [45, 80],
    prep: "Avoid combo",
    tags: ["Two mains", "Choose one"],
    ingredients: ["One chicken wrap", "Four fried chicken tenders"],
    steps: ["Choose either the wrap or a smaller strip portion.", "Do not use protein content to treat a high-energy double order as a fitness meal.", "Skip dips, dessert and calorie drinks."],
    note: "Protein can be high while the overall order still makes a calorie deficit difficult.",
  },
  {
    id: "cake-jar",
    category: "limit",
    name: "Chocolate cake jar",
    strap: "Dense layers of cake, cream and sauce are easy to eat quickly.",
    portion: "1 restaurant dessert jar",
    kcal: [450, 850],
    protein: [4, 10],
    prep: "Avoid as meal",
    tags: ["Dessert", "Reset pause"],
    ingredients: ["One cake jar"],
    steps: ["Do not use a cake jar as dinner.", "During the four-week reset, leave it out completely.", "Later, choose one small dessert after a proper meal, not alongside another delivery treat."],
    note: "Jar sizes and cream content vary too much for a narrow estimate.",
  },
  {
    id: "dream-cake-tub",
    category: "limit",
    name: "Chocolate dream-cake tub",
    strap: "A shareable dessert can silently become a very large single-person portion.",
    portion: "1 full delivery tub",
    kcal: [700, 1300],
    protein: [6, 14],
    prep: "Avoid now",
    tags: ["Reset pause", "Not dinner"],
    comparable: false,
    ingredients: ["One full chocolate dream-cake tub"],
    steps: ["Keep this out during the initial reset.", "Do not order it together with another jar or use it in place of dinner.", "If reintroduced later, share a small portion after food."],
    note: "The estimate is intentionally wide; many shops do not publish weights or nutrition information.",
  },
  {
    id: "oreo-milkshake",
    category: "limit",
    name: "Oreo milkshake",
    strap: "A drink can carry the energy of a meal without the same fullness.",
    portion: "1 cafe glass",
    kcal: [500, 900],
    protein: [7, 15],
    prep: "Avoid now",
    tags: ["Liquid calories", "Reset pause"],
    ingredients: ["One cafe Oreo milkshake"],
    steps: ["Pause it during the four-week reset.", "Choose water with delivery food.", "If reintroduced, treat one small shake as the entire flex item—not an add-on."],
    note: "Ice cream, cookies, syrup and glass size cause extreme variation.",
  },
  {
    id: "strawberry-milkshake",
    category: "limit",
    name: "Sweet strawberry milkshake",
    strap: "Fruit flavour does not make a syrup-and-ice-cream drink equivalent to fruit.",
    portion: "1 cafe glass",
    kcal: [350, 700],
    protein: [6, 13],
    prep: "Limit",
    tags: ["Liquid calories", "Not fruit"],
    ingredients: ["One cafe strawberry milkshake"],
    steps: ["Ask whether it uses fresh fruit or syrup, but still treat it as a sweet drink.", "Choose whole fruit most of the time.", "Do not pair it with the weekly delivery treat."],
    note: "A plain homemade milk-and-fruit blend would be a different, easier-to-estimate item.",
  },
  {
    id: "packaged-milkshake",
    category: "limit",
    name: "Packaged flavoured milkshake",
    strap: "Convenient, but usually sweetened and less useful than plain milk.",
    portion: "1 bottle or carton, 180–250 ml",
    kcal: [180, 350],
    protein: [5, 10],
    prep: "Limit",
    tags: ["Check label", "Sweet drink"],
    ingredients: ["One packaged flavoured milk drink"],
    steps: ["Read the per-pack calories, not only the per-100 ml number.", "Choose plain UHT milk when possible.", "Finish immediately after opening without refrigeration."],
    note: "The package label should replace this estimate because products vary widely.",
  },
  {
    id: "chips-large-pack",
    category: "limit",
    name: "Large chips or Kurkure packet",
    strap: "Bulk buying turns boredom eating into several unplanned portions.",
    portion: "1 large 90–120 g packet",
    kcal: [480, 680],
    protein: [5, 9],
    prep: "Avoid bulk",
    tags: ["Boredom trigger", "Reset pause"],
    ingredients: ["One large packet"],
    steps: ["Do not keep bulk packets in the room during the initial reset.", "If reintroduced, buy the smallest single pack and put it in a bowl.", "Do not eat directly from a multipack while working."],
    note: "Use the label for the exact packet. The key issue is the easy-to-miss number of servings per pack.",
  },
  {
    id: "biscuit-sleeve",
    category: "limit",
    name: "Biscuit sleeve",
    strap: "Small pieces make the full packet easy to underestimate.",
    portion: "1 common 100–150 g sleeve",
    kcal: [450, 750],
    protein: [5, 12],
    prep: "Avoid bulk",
    tags: ["Pack trigger", "Low fullness"],
    ingredients: ["One biscuit sleeve"],
    steps: ["Do not make biscuits the substitute for lunch or dinner.", "Keep large sleeves out of the room during the reset.", "If you later want biscuits, buy a single tiny pack after a real meal."],
    note: "Read servings per pack; front-of-pack claims like digestive or multigrain do not make an unlimited portion.",
  },
  {
    id: "chocolate-bar",
    category: "limit",
    name: "Large chocolate bar",
    strap: "Compact energy with little volume, especially while distracted.",
    portion: "1 large 80–100 g bar",
    kcal: [430, 600],
    protein: [4, 9],
    prep: "Limit",
    tags: ["Dessert", "Portion first"],
    ingredients: ["One large chocolate bar"],
    steps: ["Avoid storing large bars during the reset.", "If reintroduced, choose a small individually wrapped portion.", "Eat it after a proper meal rather than when very hungry."],
    note: "Use the package label for exact values.",
  },
  {
    id: "ice-cream-tub",
    category: "limit",
    name: "Ice-cream tub",
    strap: "A multi-serving container should not become a single sitting.",
    portion: "1 small 450–500 ml tub",
    kcal: [750, 1200],
    protein: [10, 20],
    prep: "Avoid tub",
    tags: ["Multi-serve", "No freezer"],
    comparable: false,
    ingredients: ["One small ice-cream tub"],
    steps: ["Do not order a tub to an unrefrigerated room.", "If having ice cream later, buy one single-serving cup and eat it at once.", "Keep it separate from the weekly delivery main."],
    note: "Without a freezer, melted ice cream cannot be safely stored or refrozen in the room.",
  },
  {
    id: "sweet-granola-bowl",
    category: "limit",
    name: "Large sweet granola bowl",
    strap: "Granola sounds light but is dense, and free-pouring makes portions grow.",
    portion: "80–100 g granola + 250 ml milk",
    kcal: [500, 750],
    protein: [14, 22],
    prep: "Portion carefully",
    tags: ["Check label", "Not diet food"],
    ingredients: ["80–100 g sweetened granola", "250 ml milk"],
    steps: ["Use the serving weight on the label instead of filling a large bowl.", "Prefer plain oats when you want a larger-volume option.", "Use a single UHT carton and finish it after opening."],
    note: "Granola is not forbidden, but it is a poor default dinner and varies sharply by added sugar, nuts and oil.",
  },
  {
    id: "parotta-kurma",
    category: "limit",
    name: "Parotta with kurma",
    strap: "Layered parotta and oily gravy can be heavier than the plate looks.",
    portion: "2 parottas + 1 bowl kurma",
    kcal: [600, 950],
    protein: [10, 20],
    prep: "Occasional",
    tags: ["PG / outside", "Variable"],
    ingredients: ["Two parottas", "One bowl vegetable or chicken kurma"],
    steps: ["If this is the available PG breakfast, keep it to the served portion rather than adding an outside order.", "Choose chapati, idiyappam or pongal on other days when available.", "Do not treat it as a protein-rich chicken meal unless the serving has meaningful chicken."],
    note: "This is a reference for an occasional available meal, not a recommended restaurant order.",
  },
  {
    id: "cake-dinner-combo",
    category: "limit",
    name: "Dream cake + cake jar dinner",
    strap: "Two desserts replacing dinner delivers little useful protein or fullness.",
    portion: "1 dream-cake tub + 1 cake jar",
    kcal: [1200, 2100],
    protein: [10, 24],
    prep: "Avoid",
    tags: ["Double order", "Not a meal"],
    comparable: false,
    ingredients: ["One dream-cake tub", "One cake jar"],
    steps: ["Remove this combination completely during the reset.", "When hungry, choose a proper food portion before deciding about dessert.", "Do not compensate the next day; simply return to ordinary portions."],
    note: "This broad estimate shows why two desserts can approach a full reference day, not an exact calorie claim.",
  },
  {
    id: "whey-banana-blend",
    category: "no-cook",
    name: "Chocolate whey banana blend",
    strap: "A sweet protein option for the month when whey becomes affordable.",
    portion: "1 scoop whey + 1 banana + water + 1 tsp cocoa",
    kcal: [210, 300],
    protein: [22, 30],
    prep: "3 min",
    tags: ["Blender", "High protein"],
    ingredients: ["One labelled scoop of whey", "One banana", "250–350 ml safe drinking water", "One teaspoon unsweetened cocoa, optional"],
    steps: ["Blend the banana with water first.", "Add whey and cocoa, then blend briefly until smooth.", "Drink immediately and rinse the blender before residue dries."],
    note: "Use the whey label for the exact scoop values. Whey is a convenient protein source, not a complete meal by itself.",
  },
  {
    id: "plain-muesli-fruit-cup",
    category: "no-cook",
    name: "Plain muesli fruit cup",
    strap: "A measured cereal bowl that avoids the free-poured granola trap.",
    portion: "40 g low-sugar muesli + 250 ml UHT milk + 1 small fruit",
    kcal: [330, 470],
    protein: [11, 18],
    prep: "4 min",
    tags: ["Check label", "Eat now"],
    ingredients: ["About 40 g muesli with no chocolate clusters", "One small 250 ml UHT milk carton", "One small apple, orange or banana"],
    steps: ["Use the pack serving or four level tablespoons rather than filling the bowl.", "Add the milk and chopped fruit.", "Finish immediately; do not leave opened milk or a soaked bowl in the room."],
    note: "Brands vary sharply in sugar, nuts and oil. Plain oats remain the simpler low-cost default.",
  },
  {
    id: "sattu-roti-pockets",
    category: "no-cook",
    name: "Savoury sattu roti pockets",
    strap: "Shelf-stable sattu turns fresh PG rotis into a more substantial meal.",
    portion: "2 medium rotis + 40 g sattu paste + cucumber",
    kcal: [350, 500],
    protein: [14, 21],
    prep: "6 min",
    tags: ["Budget", "No fridge"],
    ingredients: ["Two fresh medium rotis", "Four level tablespoons sattu, about 40 g", "Water, lemon, cumin and chilli", "Half a cucumber"],
    steps: ["Mix sattu, seasoning and just enough water into a thick spread.", "Spread across the rotis and add cucumber strips.", "Fold and eat while the rotis are fresh."],
    note: "This is useful when lunch access is poor. It is moderate in protein rather than equivalent to a chicken or whey serving.",
  },
  {
    id: "bread-omelette-pan",
    category: "pan",
    name: "Measured-oil bread omelette",
    strap: "A familiar pan meal with the oil and bread kept visible.",
    portion: "2 eggs + 2 bread slices + vegetables + 1 tsp oil",
    kcal: [310, 430],
    protein: [16, 22],
    prep: "12 min",
    tags: ["Beginner", "One pan"],
    ingredients: ["Two eggs", "Two bread slices", "Chopped onion, tomato or chilli", "One measured teaspoon oil", "Salt and pepper"],
    steps: ["Beat the eggs with chopped vegetables and seasoning.", "Heat one teaspoon oil and cook until the egg is firm on both sides.", "Toast or warm the bread in the same pan and eat promptly."],
    note: "Cheese, butter and mayonnaise would move this above the shown range; add them only when you intend to count them as part of the portion.",
  },
  {
    id: "vegetable-poha-pan",
    category: "pan",
    name: "Quick vegetable poha",
    strap: "A cheap, light pan meal that works better with a protein add-on.",
    portion: "60 g dry poha + vegetables + 10 g peanuts + 1 tsp oil",
    kcal: [300, 410],
    protein: [7, 12],
    prep: "15 min",
    tags: ["Budget", "One pan"],
    ingredients: ["About 60 g dry poha", "Half an onion and any easy vegetables", "One tablespoon peanuts, about 10 g", "One teaspoon oil", "Turmeric, chilli, lemon and salt"],
    steps: ["Rinse the poha briefly and drain.", "Cook onion, vegetables and peanuts in the measured oil.", "Fold in poha and spices for a few minutes; finish with lemon."],
    note: "Poha is mainly a carbohydrate base. Add whey, milk, eggs, dal, chana or chicken elsewhere when the day is otherwise protein-light.",
  },
  {
    id: "ready-dal-roti-pan",
    category: "pan",
    name: "Ready-dal roti plate",
    strap: "A sealed shelf-stable pouch can rescue dinner without a delivery combo.",
    portion: "1 single-serve dal pouch, 200–250 g + 2 medium rotis",
    kcal: [420, 650],
    protein: [16, 26],
    prep: "8 min",
    tags: ["Store-bought", "Shelf-stable"],
    ingredients: ["One unopened single-serve ready-to-eat dal pouch", "Two fresh PG or packaged rotis", "Cucumber or whole fruit, optional"],
    steps: ["Check that the pouch is intact and in date.", "Empty it into a pan and heat until steaming throughout, following the label.", "Eat the full opened pouch now; do not keep leftovers without refrigeration."],
    note: "Use the pack label in place of this estimate. Choose a pouch with a short ingredient list and compare sodium when two options are similar.",
  },
  {
    id: "mosambi",
    category: "produce",
    name: "Mosambi / sweet lime",
    strap: "A Chennai-friendly whole fruit that travels better than a juice glass.",
    portion: "1 medium sweet lime",
    kcal: [55, 90],
    protein: [1, 2],
    prep: "Peel",
    tags: ["Whole fruit", "No fridge"],
    ingredients: ["One whole sweet lime"],
    steps: ["Wash the outside before peeling.", "Eat the segments rather than straining them into juice.", "Discard fruit that is mouldy, leaking or fermented-smelling."],
    note: "Whole fruit keeps more fibre and is usually more filling than the same fruit served as juice.",
  },
  {
    id: "watermelon-bowl",
    category: "produce",
    name: "Fresh watermelon bowl",
    strap: "High-volume fruit for hot days when bought as one fresh serving.",
    portion: "1 heaped bowl, about 250 g",
    kcal: [65, 100],
    protein: [1, 2],
    prep: "Eat now",
    tags: ["Fresh cut", "Hydrating"],
    ingredients: ["One freshly cut 250 g serving from a clean source"],
    steps: ["Buy only the amount you will eat immediately.", "Choose chilled or freshly cut fruit from a clean vendor.", "Do not store an opened or cut portion in the room."],
    note: "Cut melon is perishable. Whole uncut fruit and an immediate single serving are safer fits for a no-fridge room.",
  },
  {
    id: "grapes-small-bowl",
    category: "produce",
    name: "Small bowl of grapes",
    strap: "Sweet whole fruit with a visible bowl boundary.",
    portion: "1 small bowl, about 150 g",
    kcal: [90, 125],
    protein: [1, 2],
    prep: "Wash",
    tags: ["Whole fruit", "Portion first"],
    ingredients: ["About 150 g fresh grapes"],
    steps: ["Wash under clean running water and drain.", "Place one serving in a bowl instead of eating from a large bag.", "Buy a small quantity that can be eaten the same day in hot weather."],
    note: "Grapes are ordinary fruit, not unlimited. The bowl boundary is useful because small pieces are easy to eat while distracted.",
  },
  {
    id: "uht-soy-milk",
    category: "protein",
    name: "Unsweetened UHT soy milk",
    strap: "A shelf-stable plant option when the label shows useful protein.",
    portion: "1 small carton, 200–250 ml",
    kcal: [80, 150],
    protein: [7, 11],
    prep: "Open + drink",
    tags: ["Check label", "Drink now"],
    ingredients: ["One unopened plain or unsweetened UHT soy drink carton"],
    steps: ["Compare protein and added sugar per full carton.", "Shake, open and drink the whole small carton.", "Do not keep an opened carton in the room."],
    note: "Some soy drinks contain very little soy or substantial added sugar, so the package label matters more than the front name.",
  },
  {
    id: "ready-chana-pouch",
    category: "protein",
    name: "Ready-to-eat chana pouch",
    strap: "A sealed cupboard protein that needs no soaking or batch cooking.",
    portion: "1 plain 180–250 g pouch, drained if packed in liquid",
    kcal: [240, 380],
    protein: [12, 20],
    prep: "Open + eat",
    tags: ["Shelf-stable", "Budget"],
    ingredients: ["One intact ready-to-eat chickpea or kala-chana pouch", "Lemon, cucumber and spices, optional"],
    steps: ["Check the label and avoid a swollen, leaking or damaged pouch.", "Drain if needed, season and eat the entire opened single serving.", "Heat according to the pack if the product requires heating."],
    note: "Plain chana is easier to estimate than oily ready-made chana masala. Sodium varies, so compare labels when possible.",
  },
  {
    id: "skim-milk-powder",
    category: "protein",
    name: "Skim milk-powder drink",
    strap: "A dry cupboard option when fresh milk access is unreliable.",
    portion: "30 g skim milk powder mixed with 250 ml safe water",
    kcal: [100, 140],
    protein: [9, 12],
    prep: "2 min",
    tags: ["Shelf-stable", "Check label"],
    ingredients: ["About 30 g skimmed milk powder", "250 ml safe drinking water"],
    steps: ["Confirm the product is skim milk powder rather than a sweet dairy whitener.", "Mix a little water into a smooth paste, then add the rest.", "Drink immediately and keep the dry powder sealed."],
    note: "The label should replace this estimate. Dairy whitener, malt drink and infant formula are different products and should not be substituted here.",
  },
  {
    id: "single-chicken-burger",
    category: "limit",
    name: "Single chicken burger",
    strap: "One burger can be the whole occasional main without becoming a combo.",
    portion: "1 regular chicken burger",
    kcal: [350, 650],
    protein: [15, 30],
    prep: "Occasional",
    tags: ["One main", "Skip combo"],
    ingredients: ["One regular chicken burger"],
    steps: ["Order one regular burger rather than two.", "Use water and leave out fries, fried chicken and dessert from the same order.", "Return to ordinary food next time without compensating or skipping meals."],
    note: "Patty style, mayonnaise, cheese and bun size create the wide range.",
  },
  {
    id: "full-medium-pizza",
    category: "limit",
    name: "Full medium pizza",
    strap: "A pizza sold as one box often contains several useful portions.",
    portion: "1 full medium 8-slice pizza",
    kcal: [1200, 2200],
    protein: [45, 90],
    prep: "Avoid solo box",
    tags: ["Multi-serve", "Share it"],
    comparable: false,
    ingredients: ["One full medium restaurant pizza"],
    steps: ["Do not treat the whole box as the default personal portion.", "Share it or order the smallest size available.", "Keep garlic bread, wings and sweet drinks out of the same order."],
    note: "Crust, cheese, toppings and shop size vary too much for this whole-box reference to belong in the comparison tray.",
  },
  {
    id: "fried-chicken-bucket",
    category: "limit",
    name: "Fried chicken bucket",
    strap: "A sharing format makes the stopping point disappear when eating alone.",
    portion: "1 common 8-piece bucket",
    kcal: [1600, 2800],
    protein: [90, 160],
    prep: "Avoid solo bucket",
    tags: ["Multi-serve", "Fried"],
    comparable: false,
    ingredients: ["One eight-piece fried chicken bucket"],
    steps: ["Do not order a sharing bucket for one person.", "If fried chicken is the flex choice, select a small individual portion without fries or dessert.", "Eat it as the main, not as a side to a burger or wrap."],
    note: "Piece size, coating, skin and oil absorption make the full bucket too variable for the comparison tray.",
  },
  {
    id: "biryani-starter-combo",
    category: "limit",
    name: "Biryani + fried starter",
    strap: "Two restaurant mains arrive in one order even when one is labelled a starter.",
    portion: "1 biryani box + 1 fried chicken starter",
    kcal: [1200, 2100],
    protein: [45, 85],
    prep: "Avoid combo",
    tags: ["Two mains", "High impact"],
    comparable: false,
    ingredients: ["One restaurant biryani", "One chilli chicken, chicken 65 or fried starter portion"],
    steps: ["Choose the biryani or the starter-led meal, not both.", "If choosing biryani, use the chicken in it and stop after one box.", "Use water and leave dessert for another occasion."],
    note: "Oil, rice quantity and starter size vary sharply, so this combination stays a boundary reference rather than a tray item.",
  },
  {
    id: "white-sauce-pasta",
    category: "limit",
    name: "Creamy white-sauce pasta",
    strap: "Cream, cheese and restaurant oil can make a soft bowl deceptively dense.",
    portion: "1 restaurant bowl",
    kcal: [700, 1200],
    protein: [15, 32],
    prep: "Occasional",
    tags: ["Creamy", "Variable"],
    ingredients: ["One restaurant white-sauce pasta bowl"],
    steps: ["Treat one bowl as the full main.", "Do not add garlic bread, fries or a milkshake.", "Choose tomato-based or visibly less creamy pasta when that is the option you enjoy."],
    note: "Restaurant recipes vary in butter, cream, cheese and serving size, so the range is intentionally broad.",
  },
  {
    id: "fried-momos",
    category: "limit",
    name: "Fried momos with dip",
    strap: "Frying and creamy dip can double the impact of an otherwise small-looking plate.",
    portion: "8 fried chicken or paneer momos + dip",
    kcal: [600, 1000],
    protein: [18, 34],
    prep: "Limit",
    tags: ["Fried", "Dip adds up"],
    ingredients: ["Eight fried momos", "One served dip"],
    steps: ["Choose steamed momos when you mainly want the filling and flavour.", "If choosing fried, keep it to one plate and use the dip lightly.", "Do not add noodles, fried rice or a sweet drink."],
    note: "Wrapper size, filling and frying oil change the estimate substantially.",
  },
  {
    id: "samosa-bajji-plate",
    category: "limit",
    name: "Samosa or bajji plate",
    strap: "Several tea-shop pieces can become a meal without providing much protein.",
    portion: "4 medium fried pieces",
    kcal: [400, 800],
    protein: [7, 16],
    prep: "Limit",
    tags: ["Fried snack", "Low protein"],
    ingredients: ["Four medium samosas, bajjis or bondas"],
    steps: ["Choose one or two pieces when you genuinely want the snack rather than ordering a full mixed plate.", "Do not use several fried pieces as the only lunch.", "Pair the next normal meal with protein instead of compensating by fasting."],
    note: "Piece size, batter and absorbed oil cause the wide range.",
  },
  {
    id: "bakery-puff-pair",
    category: "limit",
    name: "Two bakery chicken puffs",
    strap: "Flaky pastry carries more fat than the small filling suggests.",
    portion: "2 medium chicken or egg puffs",
    kcal: [500, 900],
    protein: [14, 28],
    prep: "Limit pair",
    tags: ["Bakery", "Choose one"],
    ingredients: ["Two medium savoury bakery puffs"],
    steps: ["Choose one puff if it is the item you want.", "Do not mistake a chicken label for a high-protein meal; pastry is most of the portion.", "Add water or whole fruit rather than a sweet drink."],
    note: "Bakery puff size, shortening and filling vary widely.",
  },
  {
    id: "soft-drink-bottle",
    category: "limit",
    name: "Large soft-drink bottle",
    strap: "Sweet liquid adds energy to an order without solving hunger.",
    portion: "1 common 600 ml bottle",
    kcal: [240, 280],
    protein: [0, 0],
    prep: "Skip default",
    tags: ["Liquid calories", "No protein"],
    ingredients: ["One 600 ml sugar-sweetened soft drink"],
    steps: ["Use water as the automatic delivery drink.", "If you specifically want a soft drink, choose the smallest single serving and make it the sweet item.", "Do not pair it with a milkshake or dessert."],
    note: "The package label gives the exact number; this range covers common full-sugar products, not zero-sugar drinks.",
  },
  {
    id: "double-instant-noodles",
    category: "limit",
    name: "Double instant-noodle packet",
    strap: "Two packets feel like a cheap dinner but remain mostly refined starch and oil.",
    portion: "2 standard noodle packets prepared together",
    kcal: [700, 1000],
    protein: [14, 24],
    prep: "Limit double",
    tags: ["Double portion", "High sodium"],
    ingredients: ["Two standard instant-noodle packets and both seasoning sachets"],
    steps: ["Prepare one packet when noodles are the choice.", "Add an egg or soy and vegetables if accessible rather than opening a second packet.", "Use less of the seasoning if sodium is a concern and do not save cooked leftovers in the room."],
    note: "Read the full-packet label; some brands display values per half packet or per 100 g.",
  },
];
